[package]
name = "git-repo-manager"
version = "0.7.9"
edition = "2021"

authors = [
  "Hannes Körber <hannes@hkoerber.de>",
]
description = """
Manage multiple git repositories.
You configure the git repositories in a file, the program does the rest!
"""

keywords = ["git"]
categories = [
  "command-line-utilities",
  "development-tools",
]

homepage = "https://github.com/hakoerber/git-repo-manager"
repository = "https://github.com/hakoerber/git-repo-manager"

readme = "README.md"

# Required for `std::path::Path::is_symlink()`. Will be released with 1.57.
rust-version = "1.57"

license = "GPL-3.0-only"

[profile.e2e-tests]
inherits = "dev"

[lib]
name = "grm"
path = "src/lib.rs"

[[bin]]
name = "grm"
path = "src/grm/main.rs"

[dependencies]

[dependencies.toml]
version = "=0.5.9"

[dependencies.serde]
version = "=1.0.145"
features = ["derive"]

[dependencies.git2]
version = "=0.15.0"

[dependencies.shellexpand]
version = "=2.1.2"

[dependencies.clap]
version = "=4.0.11"
features = ["derive", "cargo"]

[dependencies.console]
version = "=0.15.2"

[dependencies.regex]
version = "=1.6.0"

[dependencies.comfy-table]
version = "=6.1.0"

[dependencies.serde_yaml]
version = "=0.9.13"

[dependencies.serde_json]
version = "=1.0.85"

[dependencies.isahc]
version = "=1.7.2"
default-features = false
features = ["json", "http2", "text-decoding"]

[dependencies.parse_link_header]
version = "=0.3.2"

[dependencies.url-escape]
version = "=0.1.1"

[dev-dependencies.tempdir]
version = "=0.3.7"

[features]
static-build = [
  "git2/vendored-openssl",
  "git2/vendored-libgit2",
  "isahc/static-curl",
  "isahc/static-ssl",
]
