[book]
authors = ["Hannes Körber"]
language = "en"
multilingual = false
src = "src"
title = "Git Repo Manager"

[output.html]
mathjax-support = true

# [output.linkcheck]
# follow-web-links = true
# traverse-parent-directories = false
# warning-policy = "error"
